### ISSUE TITLE
Unable to connect to `Matrix8x8` via address on Joy-Pi

### ISSUE THREAD

**Issue by ero-qt** [adafruit/Adafruit_CircuitPython_HT16K33#116]
For a school project, I am required to access a [Joy-Pi](https://joy-it.net/en/products/rb-joypi)'s 8x8 matrix. I am trying to do this using `adafruit_ht16k33.matrix.Matrix8x8`:

```py
from adafruit_ht16k33.matrix                  import Matrix8x8
from adafruit_ht16k33.segments                import Seg7x4
from adafruit_dht                             import DHT11             as Dht11
from adafruit_character_lcd.character_lcd_i2c import Character_LCD_I2C as Lcd16x2

DHT_PIN     = board.D18
LCD_ADDRESS = 0x21
SEG_ADDRESS = 0x70
MTX_ADDRESS = 0x00 # Docs say 'between 0x70 and 0x77'.

# In
dht = Dht11(DHT_PIN)

# Out
i2c = board.I2C()

lcd = Lcd16x2(i2c, columns=16, lines=2, address=LCD_ADDRESS)
seg = Seg7x4(i2c, address=SEG_ADDRESS)
mtx = Matrix8x8(i2c, address=MTX_ADDRESS)
```

I have tried all addresses from `0x71` to `0x77` (I did not try `0x70` because that already belongs to the DHT). On all of these, it reports that the device does not exist. All other shown devices do work.

Is this something I am able to fix by myself? Should I contact Joy-IT instead? Am I just blatantly doing something wrong?

**Comment by makermelissa** [comment]
In the case of Adafruit's chips, the HT16K33 is the driver chip that controls the matrix. According to their manual at https://www.alcom.no/wp-content/uploads/2020/01/RB-JoyPi-Manual.pdf, it appears the Joy-Pi uses a MAX7219 chip instead, so this library will not work for you.
