### ISSUE TITLE
Add auto write?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_HT16K33#13]
Would it make sense to add a toggle-able auto-write capability, similar to neopixel. That way user doesn't have to always call `show()` to update the display and see what they sent it. I think having this on by default would be more beginner friendly, so they could just:
```python
disp.print("BEEF")
```
and it would show up right away.

It could be turned off, reverting to current behavior, for more advanced usage.

**Comment by tannewt** [comment]
Yup, I like autowrite.

**Comment by sommersoft** [comment]
Completed by #14.
