### ISSUE TITLE
Request for Seg14x8 class

### ISSUE THREAD

**Issue by pbricmont** [adafruit/Adafruit_CircuitPython_HT16K33#36]
Could someone add a Seg14x8 class to segments.py? The chip supports 8 digits using the breakout or a custom board. 

Thanks,

Paul

**Comment by ladyada** [comment]
@pbricmont do you have hardware to test against (we don't :)

**Comment by pbricmont** [comment]
@ladyada I do: https://oshpark.com/shared_projects/XATdkjXm

I have three boards built. I got them working with Arduino by hacking the backpack library. The project is a multiline IOT display. 

![IMG_6408](https://user-images.githubusercontent.com/49604112/56098230-37cf4c00-5eb3-11e9-87e5-dcdb293aff9c.jpg)
![IMG_6409](https://user-images.githubusercontent.com/49604112/56098267-98f71f80-5eb3-11e9-847c-b4e88f801fe8.jpg)

**Comment by ladyada** [comment]
@pbricmont how about you try making the variation and submit a PR :) you're the best equiped :D

**Comment by pbricmont** [comment]
@ladyada I'll give it shot. I think I can see what needs to be done but I need to learn how to build it locally.

**Comment by makermelissa** [comment]
The nice thing about CircuitPython libraries is you don't need to build them. They're just text like the regular CircuitPython scripts. I was under that same impression the first time I went to write one.

**Comment by pbricmont** [comment]
@makermelissa So I can just replace the .mpy file with the .py in a library directory and it should work (assuming I've written some functional code)?

**Comment by makermelissa** [comment]
Yes! That's exactly what I do.

**Comment by makermelissa** [comment]
I should add the caveat that as long as your board has enough memory. I am partial to Feather M4 Express boards.

**Comment by pbricmont** [comment]
@makermelissa Thank you! That makes it much easier. I've been testing with Metro M0 but I have Metro M4 and Grand Central available as well.

**Comment by makermelissa** [comment]
Perfect. That should work great.
