### ISSUE TITLE
Provide method for setting via raw bitmask

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_HT16K33#42]
Like the old library did:
https://github.com/adafruit/Adafruit_Python_LED_Backpack/blob/7356b4dd8b4bb162d60987878c2cb752fdd017d5/Adafruit_LED_Backpack/SevenSegment.py#L84

ref:
https://forums.adafruit.com/viewtopic.php?f=19&t=158151

**Comment by ladyada** [comment]
@makermelissa will be giving this repo a scrubbing soon

**Comment by caternuson** [comment]
Cool. Hopefully she can get further than my previous attempt :)
https://github.com/adafruit/Adafruit_CircuitPython_HT16K33/issues/8

**Comment by makermelissa** [comment]
I think I got this figured out for the 7-segment display and 14-segment displays. Did we need this for other types of displays too?

**Comment by makermelissa** [comment]
I have tested on the 7-segment and 14-segment featherwings as well as the large 7-segment display. Fixed via #43.
