### ISSUE TITLE
16x8 Backpack bas different layout than Featherwing

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_HT16K33#48]
It appears the 16x8 matrix backpack is laid out differently than the 16x8. Running the exact same code (the demo code), I get 2 different results:
![IMG_1514](https://user-images.githubusercontent.com/2681417/72396840-d9a9f080-36f2-11ea-9a3c-ba093ac2f9a8.jpeg)
![IMG_1515](https://user-images.githubusercontent.com/2681417/72396905-0eb64300-36f3-11ea-9ec3-38a470760f82.jpeg)

We probably either need a new Matrix object (8x16?) or to pass a parameter in to differentiate how positions are calculated.

**Comment by makermelissa** [comment]
Oops, photos updated.

**Comment by caternuson** [comment]
I'd vote for two different classes.

**Comment by makermelissa** [comment]
Thanks for the input, sounds good.

**Comment by makermelissa** [comment]
Ok, I just wanted to see what was done in the Arduino library and there are 2 different classes Adafruit_8x16matrix and Adafruit_8x16minimatrix. Since we're using Matrix16x8 for the mini one and would prefer to not break code if possible, I'll probably use something like Matrix16x8Backpack or MatrixBackpack16x8.

**Comment by Docteh** [comment]
I ended up spending a bunch of time wondering about the why. As the schematics for both 16x8 boards have the modules identically arranged. I did find the answer, the location of the pins underneath the module:
Original module 
![image](https://user-images.githubusercontent.com/190571/129287900-9cfa4453-d01e-4359-b4bf-a5f8700d89df.png)

Newer Luckylight modules, posted July 2014
![image](https://user-images.githubusercontent.com/190571/129287973-fce4ecd2-dab2-4fe7-b074-659b94ffaef5.png)
