### ISSUE TITLE
Modify the brightness property.

### ISSUE THREAD

**Issue by geekguy-wy** [adafruit/Adafruit_CircuitPython_HT16K33#62]
To make the library consistent with displayio, modify the brightness property so it uses a float instead of an int.

**Comment by caternuson** [comment]
With a range 0.0 to 1.0:
https://circuitpython.readthedocs.io/en/latest/shared-bindings/displayio/Display.html#displayio.Display.brightness

**Comment by geekguy-wy** [comment]
Got it, thanks. I already have the function to do the mapping from float to the range 0 to 15.

**Comment by geekguy-wy** [comment]
@caternuson 
Does displayio carry the brightness property all the way through as a float? 
If so, do we want the ht16k33 library to do that or can we just carry it as a 0-15 int?

My thought is that if a user sets brightness as a float and we give them back an int that it might confuse things a bit.

**Comment by makermelissa** [comment]
It's now merged in.
