### ISSUE TITLE
8-digit seven segment display

### ISSUE THREAD

**Issue by lvajxi03** [adafruit/Adafruit_CircuitPython_HT16K33#67]
Is there a tiny chance to support 8-digit 7-seg display? As we can see, HT16K33 pinout supports 8 digits, but...

**Comment by makermelissa** [comment]
Hi, do you want to submit a PR? We don't have one to test with.

**Comment by geekguy-wy** [comment]
I would love to do this, and it is one of my goals for the library. However, I do not have any of the 8-digit 7-segment displays to test with. I would also like to expand my code to support Adafruit's 7-segment displays, but I also do not have any of those to test with.

**Comment by geekguy-wy** [comment]
I would love to add support for multiple 7-segment, alphanumeric, and matrix displays. However, I only have one of the alphanumeric display Feather wings (Green) here. To do this and properly test everything, I would need at least three of each display. This is something I want very much to do. There are also the  Charlieplexed Feather wings and larger 16x9 Charlieplexed displays which are run by a different library I have not worked with yet.

**Comment by makermelissa** [comment]
@geekguy-wy, I think he was referring to something like https://ebay.us/6qYcgl which uses a single ht16k33 chip as opposed to 2 4-digit displays at different addresses. I don't have one, which is why I requested he submit a PR.

**Comment by geekguy-wy** [comment]
@makermelissa Yes, I know :) I was just expressing my desire to extend the support for Adafruit displays to allow the use of multiples in sort of a "chain." I thought that could be included in this issue, but I can open a separate one if you prefer that.

**Comment by makermelissa** [comment]
I hear what you're saying and it's a great idea. I think a separate issue would be appropriate. :)
