### ISSUE TITLE
Default brightness should be an instantiation paramenter

### ISSUE THREAD

**Issue by geekguy-wy** [adafruit/Adafruit_CircuitPython_HT16K33#68]
When somebody instantiates one of these classes, they should be able to set the default brightness. I want to add a brightness=15 parameter to the constructors to make this possible.  This would preserve the current startup state.

**Comment by makermelissa** [comment]
Great idea. Would you like to submit a PR?

**Comment by geekguy-wy** [comment]
Yes, of course. The change is easy enough to make.

**Comment by makermelissa** [comment]
It's now merged in.
