### ISSUE TITLE
Pylint: arguments-out-of-order

### ISSUE THREAD

**Issue by evaherrada** [adafruit/Adafruit_CircuitPython_HT16K33#72]
The Pylint failure:
```
************* Module adafruit_ht16k33.matrix
adafruit_ht16k33/matrix.py:176:15: W1114: Positional arguments appear to be out of order (arguments-out-of-order)
```
The line in question
`176        return super()._pixel(y, x, color)`

Are these arguments actually out of order or should I add a disable?

Referencing main issue: adafruit/Adafruit_CircuitPython_Bundle#232
@kattni

**Comment by tannewt** [comment]
This looks intentional to me and needs a pylint exception. @makermelissa would know for sure.

**Comment by makermelissa** [comment]
Yep, disable please.

**Comment by evaherrada** [comment]
@makermelissa @tannewt Ok. I've disabled it. Thanks

**Comment by kattni** [comment]
Closing this issue. PR is in process.
