### ISSUE TITLE
Add the animate() function from the example to the library.

### ISSUE THREAD

**Issue by geekguy-wy** [adafruit/Adafruit_CircuitPython_HT16K33#75]
The animate() function that provides the animation ability for the alphanumeric displays should be moved from the animation example to the library.

**Comment by jposada202020** [comment]
Could we just create a new file with the animation code, not sure all folks needs this functionality?. @makermelissa what do you think?

**Comment by makermelissa** [comment]
Yes, a new file makes sense.

**Comment by jposada202020** [comment]
This was solved by #88.Thanks 👍🏼
